### ISSUE TITLE
Problem with programs and tools

### ISSUE THREAD

**Issue by charayb** [ArtanisInc/Post-Tweaks#1]
Don´t know how to confirm the choices or where do they download
![image](https://user-images.githubusercontent.com/78571919/106969950-a5083d00-672a-11eb-9dd6-e052e67d9a16.png)
(stuck here)

**Comment by ArtanisInc** [comment]
To confirm your choices you need to press ENTER button. When programs are downloaded the script will open their location (documents folder).
