### ISSUE TITLE
Virus Total malware scan

### ISSUE THREAD

**Issue by DDL56x** [ArtanisInc/Post-Tweaks#15]
While downloading the latest version 2.1.3 (03/04/2022) of Win 10 Post-Tweaks VT's AV vendors flagged 4 potential malware infections within the zipfile:

https://www.virustotal.com/gui/file/7a8822ec371f180a6aee533a124db17c790ee9a623d0444aede89cd4b581deaf

**Comment by ArtanisInc** [comment]
All thoses detection are related to the .exe files and are false positive.
The source code of the .exe files : 
https://github.com/M2Team/NSudo
https://www.robvanderwoude.com/dialogboxes.php
https://github.com/Orbmu2k/nvidiaProfileInspector
https://forums.guru3d.com/threads/windows-timer-resolution-tool-in-form-of-system-service.376458/
