### ISSUE TITLE
Kernel Security Checks

### ISSUE THREAD

**Issue by Canderous599** [ArtanisInc/Post-Tweaks#16]
Hi, 
It looks like I have an issue related to fvevol and rdyboost deactivation. 
i tried to stop them earlier deleting lowerfilters and dependances, and cant boot with a KERNEL SECURITY CHECK FAILURE blue screen. 
That’s how I found your script, 
And after applying it I have the same error, that’s why I think it’s the same problem. 

Do you have any fix for it ? 

Thanks

**Comment by ArtanisInc** [comment]
If I understand your problem has nothing to do with my script, you already had this problem before using my script ?
If so, add on discord Artanis#5658 I will try to help you.
