### ISSUE TITLE
Cant open any windows settings menu and searching cant find the create a restore point window

### ISSUE THREAD

**Issue by crooklyndoom** [ArtanisInc/Post-Tweaks#18]
I didnt disable system restore points so I am not sure what I can do to fix other than make a new installation

Any help is appreciated, Thank you

**Comment by ArtanisInc** [comment]
Do you have discord by any chance ? if so add me so I can help you Artanis#5658

**Comment by ArtanisInc** [comment]
Use this powershell command:
if your are on 1909 or older
`Get-AppxPackage -AllUsers Microsoft.Windows.Cortana | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}`
if your are on 2004 or newer
`Get-AppxPackage -AllUsers Microsoft.549981C3F5F10 | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}`
