### ISSUE TITLE
Bitlocker won't work

### ISSUE THREAD

**Issue by matagul** [ArtanisInc/Post-Tweaks#19]
After use, bitlocker just stop working. I tried registry edit, manually start services and start from cmd but no luck.... Any help ?

**Comment by matagul** [comment]
wow. just checked with 3rd party softwares, my external drive is completely f.up. great work!

**Comment by ArtanisInc** [comment]
Do you have discord by any chance ? if so add me so I can help you Artanis#5658
It's probably related to a device that the script disable.

**Comment by ArtanisInc** [comment]
Use this command on your console
`reg add "HKLM\SYSTEM\CurrentControlSet\Services\fvevol" /v "Start" /t REG_DWORD /d "0" /f`
if the problem persists, contact me on discord
