### ISSUE TITLE
Network icon, gui boot and action centre gone

### ISSUE THREAD

**Issue by michaelbash** [ArtanisInc/Post-Tweaks#2]
Hey, awesome script. It really does make a lotta difference in performance. However, how can I make network icon in taskbar, gui during boot and action centre work again? Its otherwise perfect. Also after running the script msconfig rejects any new changes.

Thanks

**Comment by ArtanisInc** [comment]
Sorry for late reply.

To retrieve the GUI during boot, type this on cmd:
bcdedit /deletevalue quietboot
bcdedit /deletevalue {globalsettings} custom:16000067
bcdedit /deletevalue {globalsettings} custom:16000068
bcdedit /deletevalue {globalsettings} custom:16000069

For action center:
reg delete "HKCU\SOFTWARE\Policies\Microsoft\Windows\Explorer" /v "DisableNotificationCenter" /f

I need more information about the network icon problem, are you using a static IP address and are you using wifi or ethernet ?

**Comment by michaelbash** [comment]
Thanks for the answers, I use ethernet. If Im not mistaken the script sets ip as static, otherwise I use automatic ip via dhcp.

**Comment by ArtanisInc** [comment]
Try enabling "dhcp" service for the network icon issue
reg add "HKLM\SYSTEM\CurrentControlSet\Services\Dhcp" /v "Start" /t REG_DWORD /d "2" /f
