### ISSUE TITLE
Improvement about gpu recognition

### ISSUE THREAD

**Issue by Vojtazz** [ArtanisInc/Post-Tweaks#21]
Hello again,

Is it possible to recognize GPU without a gpu driver. can you add it?

If I want to use your script settings are not applying and the variable is not setting correctly.

Cheers

**Comment by ArtanisInc** [comment]
This is not possible without a third party program, the only way to recognize GPU without GPU driver is by Vendor ID.
You need a list of each vendor ID along with the gpu model... Also if I am not mistaken some settings applied by the script are overridden by the GPU after the driver installation.

**Comment by Vojtazz** [comment]
> This is not possible without a third party program, the only way to recognize GPU without GPU driver is by Vendor ID. You need a list of each vendor ID along with the GPU model… Also, if I am not mistaken some settings applied by the script are overridden by the GPU driver after its installation.

Ok, can you please fix one thing?
SSD recognition still now works. On hdd drive it outputs SSD. It is still broken.

**Comment by ArtanisInc** [comment]
> Ok, can you please fix one thing? SSD recognition still now works. On hdd drive it outputs SSD. It is still broken.

You probably downloaded the script inthe release section. I didn't creat a new release yet but you can download the script here https://github.com/ArtanisInc/Post-Tweaks/blob/main/PostTweaks.bat

**Comment by Vojtazz** [comment]
Sorry for bothering you, but I am tired of that. On ssd and hdd outputs ECHO IS OFF. Tested on 5 PCS and 2 laptops. 
Can you please solbe this issue?

**Comment by ArtanisInc** [comment]
Check the new version it should be solved
