### ISSUE TITLE
the bat file freezes after a window named "Hardening"

### ISSUE THREAD

**Issue by detrimenttalfy** [ArtanisInc/Post-Tweaks#22]
after I click "OK" this window will disappear and nothing will happen anymore. I sat with the "Post tweaks" open for about 10 minutes and nothing happened
![Screenshot_1](https://user-images.githubusercontent.com/105291485/167631861-815bd508-f70f-49ad-b30b-836abe1ad72d.png)

**Comment by detrimenttalfy** [comment]
I tried to choose "Block untrusted fonts" but nothing has changed

**Comment by ArtanisInc** [comment]
Issue solved with the new version 2.1.9
