### ISSUE TITLE
UNMOUNTED_BOOT_VOLUME

### ISSUE THREAD

**Issue by teassin** [ArtanisInc/Post-Tweaks#26]
When using System Tweaks. I thought it will optimize my system, but it broke it. Can't factory reset, can't startup repair. Help please.

**Comment by ArtanisInc** [comment]
Hello can you elaborate please.
What is the problem that came with "System Tweaks" and did you select disable restore point ?

**Comment by Vojtazz** [comment]
> Hello can you elaborate please. What is the problem that came with "System Tweaks" and did you select disable restore point ?
> 
> Is it a bsod with the stop code UNMOUNTED_BOOT_VOLUME ?

you should close it, he is not replying
