### ISSUE TITLE
Nvidia, Razer synapse and Window Store

### ISSUE THREAD

**Issue by IGuruDevI** [ArtanisInc/Post-Tweaks#4]
I liked your work bro but I face few problems. I just used system tweak and it disabled Nvidia driver and razer synapse. I have managed to install the Nvidia driver and it working but the performance overlay in the Nvidia experience is not working. razer synapse not opening because it says service not running and the window store still can't install anything

**Comment by IGuruDevI** [comment]
network icon also missing

**Comment by slxwzin** [comment]
just edit the .bat and delete the kboost solve the nvidia problem

**Comment by hateeee1** [comment]
deleting the kboost did not help. Any other fix? @slxwzin

**Comment by ArtanisInc** [comment]
Oops... Problem solved in the 2.0.
The network icon missing was because of a service and a registry dword. Microsoft store problem is also because of a servic, but for Razer and NVIDIA driver idk... Maybe because the script remove every Microsoft store apps and keep the necessary.
