### ISSUE TITLE
Re-enable 

### ISSUE THREAD

**Issue by ToxicSodapop** [ArtanisInc/Post-Tweaks#41]
I can't re-enable hibernation, I have tried 
-------------------
`POWERCFG /h ON`
--------------------
and trying to do this (found on article)
--------------------
```
reg add "HKLM\System\CurrentControlSet\Control\Session Manager\Power" /v "HiberbootEnabled" /t REG_DWORD /d "1" /f
powercfg -h on
```
--------------------
but to no success, any way I can restore this?

**Comment by JustOptimize** [comment]
I think it's stripped out. You only have sleep which is the same thing ig.
