### ISSUE TITLE
Nvidia driver

### ISSUE THREAD

**Issue by hateeee1** [ArtanisInc/Post-Tweaks#5]
The driver wont be there when you restart.  When you restart a several times it comes back.

**Comment by ArtanisInc** [comment]
Hey,
Maybe it's related to nvidia settings or melody gpu tweaks. Anyway you can fix it by reinstalling Nvidia driver.
You can use DDU https://www.guru3d.com/files-details/display-driver-uninstaller-download.html to completely uninstall it.
You can also use Nvcleaninstall https://www.techpowerup.com/download/techpowerup-nvcleanstall/ or the official website of Nvidia https://www.nvidia.fr/Download/index.aspx

**Comment by hateeee1** [comment]
But if I ddu and reisntall the tweaks will go @ArtanisInc also what are the nvidia settings so I can delete them and try

**Comment by ArtanisInc** [comment]
Go to this path "C:\ProgramData\NVIDIA Corporation\Drs" and delete these files:
nvdrsdb0.bin
nvdrsdb1.bin

**Comment by hateeee1** [comment]
@ArtanisInc Thank you so much. Everything is soooo good.

**Comment by ArtanisInc** [comment]
It's related to Nvidia control panel settings so yes.
You can use Nvidia profile inspector https://github.com/Orbmu2k/nvidiaProfileInspector/releases/tag/2.3.0.10 and import this .nip file https://www.sendspace.com/file/jquhsa
but you will have to manually set "low latency mode" and" silk smoothness" in Nvidia control panel

**Comment by hateeee1** [comment]
So If I do those settings from profile inspector my in-game performace wont be affected in-game. Am I right?

**Comment by hateeee1** [comment]
bro, i'm sorry if I am making you go crazy xd. but how does control panel affenct my performance?

**Comment by ArtanisInc** [comment]
Add me on discord it will be much easier Artanis#5658
