### ISSUE TITLE
ERROR: The system cannot find the file specified.

### ISSUE THREAD

**Issue by tomi2iq** [ArtanisInc/Post-Tweaks#7]
![image](https://user-images.githubusercontent.com/84363849/119239734-7b88eb00-bb3a-11eb-9007-3050dbbf5f0a.png)
![image](https://user-images.githubusercontent.com/84363849/119239747-94919c00-bb3a-11eb-8552-c13cf14c18f9.png)
help

**Comment by ArtanisInc** [comment]
The github version of the script is obselete, I will release a new version soon. Also this is a problem related to https://chocolatey.org/ package :/

**Comment by ArtanisInc** [comment]
You have to install Spotify manually
