### ISSUE TITLE
Needs more explanation of what the codes does

### ISSUE THREAD

**Issue by coff33ninja** [ArtanisInc/Post-Tweaks#8]
I tested the bat on my bench system and found one fatal flaw is explanation. I used bat as an end user too optimize as what was registered on bat. But a few settings was automated without any warning of what it disabled. Took me 2 hours to fix the disabled registry entrys as to code broke system restore, registry and group policy. As well as specified drivers that's used for networking and wireless networking.
If more explanation was given then maybe other end users won't accedentally destroy their devices.

**Comment by ArtanisInc** [comment]
Hello, I apologize for the late reply and for the inconvenience caused.
I am aware of that, and I am working on a new version more user-friendly without questionable stuff, or at least with questions.
